spring.application.name=SpringAPI_Session05

#Config datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db_jb_ioc_251229_ss5
spring.datasource.username=postgres
spring.datasource.password=1234$

#Config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true



#Config pagination
pageSizeProduct = 5